### ISSUE TITLE
Error on task aws:create-cfn-bucket: Missing required key \'Bucket\' in params

### ISSUE THREAD

**Issue by vspedr** [binoculars/aws-lambda-ffmpeg#29]
It's probably a silly mistake on my side, but I'm not able to proceed with setup, being stuck at `gulp aws:create-cfn-bucket`. The command immediately fails with the following message:

```
[13:02:20] Using gulpfile ~/Projects/aws-lambda-ffmpeg/gulpfile.js
[13:02:20] Starting 'aws:create-cfn-bucket'...
{ MissingRequiredParameter: Missing required key 'Bucket' in params
    at ParamValidator.fail (/Users/victor/Projects/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/Users/victor/Projects/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (/Users/victor/Projects/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/Users/victor/Projects/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/Users/victor/Projects/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/event_listeners.js:108:42)
    at Request.callListeners (/Users/victor/Projects/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at callNextListener (/Users/victor/Projects/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at /Users/victor/Projects/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/event_listeners.js:74:9
    at finish (/Users/victor/Projects/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/config.js:308:7)
    at /Users/victor/Projects/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/config.js:324:9
  message: 'Missing required key \'Bucket\' in params',
  code: 'MissingRequiredParameter',
  time: 2017-04-03T16:02:20.871Z }
```

I noticed that this project is no longer supposed to read settings from a JSON file for AWS deployments, so I tried `export`ing the bucket names as environment variables, but still got the same error. AWS cli and credentials are correctly configured. Any directions on how to proceed?

**Comment by binoculars** [comment]
did you try setting `export CFN_S3_BUCKET=cloudformation-bucket` ?

**Comment by vspedr** [comment]
Thank you, this works. 😄 

The following part of the instructions led me to believe that I simply needed to run `gulp aws:create-cfn-bucket`, expect some string as a response and then use that string as an env variable for the next steps.

<img width="913" alt="screen shot 2017-04-03 at 15 59 13" src="https://cloud.githubusercontent.com/assets/9813942/24626308/3980f1da-1887-11e7-9e9d-10edb69d3066.png">

**Comment by binoculars** [comment]
Ah ok that is confusing. I'll reopen this as a reminder to update the README. Thanks for reporting!
