### ISSUE TITLE
deployStack fails

### ISSUE THREAD

**Issue by pieterdt** [binoculars/aws-lambda-ffmpeg#33]
I managed to get up to the deployStack gulp task which fails with the following error:

`[10:40:14] TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Parameters.map (/Users/pdt/rumspace/aws-lambda-ffmpeg/platform/aws/gulpfile.js:134:9)
    at Array.map (native)
    at Gulp.gulp.task (/Users/pdt/rumspace/aws-lambda-ffmpeg/platform/aws/gulpfile.js:134:5)
    at module.exports (/Users/pdt/rumspace/aws-lambda-ffmpeg/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/pdt/rumspace/aws-lambda-ffmpeg/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/pdt/rumspace/aws-lambda-ffmpeg/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/pdt/rumspace/aws-lambda-ffmpeg/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:46:20
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

I think CI might be undefined, but didn't see anything in the setup instructions about this:
`CI ? ['ExecutionRoleManagedPolicyArn', EXECUTION_ROLE_ARN] : undefined`

**Comment by binoculars** [comment]
just comment that out for now--tried to be slick with defining the Parameters, but that didn't work out well this time. Fix coming soon.
