### ISSUE TITLE
gulp aws:update error "InvalidParameterType: Expected params.FunctionName to be a string"

### ISSUE THREAD

**Issue by briankeane** [binoculars/aws-lambda-ffmpeg#34]
I may be doing something silly, but I'm getting this error when I try to push up changes:
```
[18:52:57] Using gulpfile ~/code/learn/aws-lambda-ffmpeg/gulpfile.js
[18:52:57] Starting 'aws:update'...
[18:52:57] Starting 'aws:build-upload'...
[18:52:57] Starting 'clean'...
[18:52:57] Finished 'clean' after 23 ms
[18:52:57] Starting 'download-ffmpeg'...
[18:53:00] Finished 'download-ffmpeg' after 3.58 s
[18:53:00] Starting 'aws:transpile'...
[18:53:00] Starting 'aws:config'...
[18:53:00] Finished 'aws:config' after 15 ms
[18:53:01] Finished 'aws:transpile' after 751 ms
[18:53:01] Starting 'aws:source'...
[18:53:01] Finished 'aws:source' after 10 μs
[18:53:01] Starting 'npm'...
[18:53:02] Finished 'npm' after 1.23 s
[18:53:02] Starting 'untar-ffmpeg'...
x ./
x ./ffmpeg
x ./ffprobe
x ./README.txt
x ./COPYING.GPLv3
[18:53:03] Finished 'untar-ffmpeg' after 367 ms
[18:53:03] Starting 'copy-ffmpeg'...
[18:53:03] Finished 'copy-ffmpeg' after 220 ms
[18:53:03] Starting 'zip'...
[18:53:06] Finished 'zip' after 3.16 s
[18:53:06] Starting 'aws:upload'...
[18:53:10] Finished 'aws:upload' after 3.41 s
[18:53:10] Finished 'aws:build-upload' after 13 s
[18:53:10] Starting 'aws:updateCode'...
[18:53:10] 'aws:updateCode' errored after 465 ms
[18:53:10] InvalidParameterType: Expected params.FunctionName to be a string
    at ParamValidator.fail (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateType (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:218:10)
    at ParamValidator.validateString (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:150:14)
    at ParamValidator.validateScalar (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:130:21)
    at ParamValidator.validateMember (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:94:21)
    at ParamValidator.validateStructure (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:75:14)
    at ParamValidator.validateMember (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/event_listeners.js:108:42)
    at Request.callListeners (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
[18:53:10] 'aws:update' errored after 13 s
[18:53:10] InvalidParameterType in plugin 'run-sequence(aws:updateCode)'
Message:
    Expected params.FunctionName to be a string
Details:
    code: InvalidParameterType
    time: Wed Apr 19 2017 18:53:10 GMT-0500 (CDT)
Stack:
InvalidParameterType: Expected params.FunctionName to be a string
    at ParamValidator.fail (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateType (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:218:10)
    at ParamValidator.validateString (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:150:14)
    at ParamValidator.validateScalar (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:130:21)
    at ParamValidator.validateMember (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:94:21)
    at ParamValidator.validateStructure (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:75:14)
    at ParamValidator.validateMember (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/event_listeners.js:108:42)
    at Request.callListeners (/Users/briankeane/code/learn/aws-lambda-ffmpeg/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
```
The only place I found "FunctionName" was in the The LamdaPermission section of cloudformation.json:
```
"LambdaPermission": {
			"Type": "AWS::Lambda::Permission",
			"DependsOn": [
				"Lambda"
			],
			"Properties": {
				"Action": "lambda:invokeFunction",
				"FunctionName": {
					"Fn::GetAtt": [
						"Lambda",
						"Arn"
					]
				},
				"Principal": "s3.amazonaws.com",
				"SourceAccount": {
					"Ref": "AWS::AccountId"
				},
				"SourceArn": {
					"Fn::Join": [
						"",
						[
							"arn:aws:s3:::",
							{
								"Ref": "SourceBucketName"
							}
						]
					]
				}
			}
		},
```
Could you give me some guidance on how to solve it?

LOVE this library, btw.  Thank you for the great work.

**Comment by binoculars** [comment]
This is a bug--when upgrading the syntax I accidentally left out the `{}` around `PhysicalResourceId ` https://github.com/binoculars/aws-lambda-ffmpeg/blob/develop/platform/aws/gulpfile.js#L171

Will fix soon. Thank you for reporting it!

**Comment by briankeane** [comment]
No prob -- thanks for building this!  Really very cool.
